# .goreleaser.yaml
builds:
  - id: "main"

    # Custom environment variables to be set during the builds.
    # Invalid environment variables will be ignored.
    #
    # Default: os.Environ() ++ env config section.
    # Templates: allowed.
    env:
      - CGO_ENABLED=0

upx:
  - # Whether to enable it or not.
    #
    # Templates: allowed.
    enabled: true
